CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_APP_USBD_PRODUCT="Zeroprobe CMSIS-DAP"
CONFIG_APP_USBD_PID=0x2ef0
CONFIG_APP_USBD_20_EXTENSION_DESC=y
CONFIG_APP_USBD_SELF_POWERED=n

CONFIG_STDOUT_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=2

CONFIG_DAP_LOG_LEVEL_INF=y
CONFIG_DP_DRIVER_LOG_LEVEL_INF=y
CONFIG_DAP=y
CONFIG_DAP_BACKEND_USB=y
CONFIG_CMSIS_DAP_PROBE_VENDOR="Zephyr"
CONFIG_CMSIS_DAP_PROBE_NAME="CMSIS-DAP"
CONFIG_CMSIS_DAP_BOARD_VENDOR="Waveshare"
CONFIG_CMSIS_DAP_BOARD_NAME="RP2040-Zero"
CONFIG_CMSIS_DAP_DEVICE_VENDOR="Generic"
CONFIG_CMSIS_DAP_DEVICE_NAME="Target"

CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_SHELL=y
CONFIG_I2C_SHELL=y

CONFIG_DEVICE_SHELL=y
CONFIG_DEVICE_SHELL_INIT_CMD=y
CONFIG_DATE_SHELL=n
CONFIG_DEVMEM_SHELL=n
CONFIG_APP_VERSION_SHELL=y
CONFIG_SHELL_MINIMAL=n
CONFIG_STATS=n

CONFIG_SPEED_OPTIMIZATIONS=y
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_BUILD_OUTPUT_STRIPPED=y