name: Build

on:
  push:
  # pull_request:
  schedule:
    - cron: "5 4 * * 0"

env:
  FIRMWARE_LIST: |
              zeroprobe/build/zephyr/zephyr.elf
              zeroprobe/build/zephyr/zephyr.uf2
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    name: Build app and tests
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: zeroprobe
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@700109a78599c7bb26585f2fb3d2411d65381b9d
        with:
          app-path: zeroprobe
          toolchains: arm-zephyr-eabi
          ccache-cache-key: ${{ matrix.os }}
          sdk-version: 1.0.1

      - name: Build firmware
        working-directory: zeroprobe
        shell: bash
        run: |
          west build

      - name: Share Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: build-artifacts-${{ matrix.os }}-${{ github.event_name }}.${{ github.sha }}
          path: ${{ env.FIRMWARE_LIST }}
          retention-days: 10
              
      - name: Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda
        if: github.ref_type == 'tag'
        with:
          files: ${{ env.FIRMWARE_LIST }}
#
#      - name: Test firmware
#        working-directory: zeroprobe
#        shell: bash
#        run: |
#          if [ "${{ runner.os }}" = "Windows" ]; then
#            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
#          fi
#          west twister -v  -p rp2040_zero --inline-logs --integration $EXTRA_TWISTER_FLAGS

      # - name: Twister Tests
      #   working-directory: zeroprobe
      #   shell: bash
      #   run: |
      #     if [ "${{ runner.os }}" = "Windows" ]; then
      #       EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
      #     fi
      #     west twister -T tests -v --inline-logs --integration $EXTRA_TWISTER_FLAGS
